"""The brand images Home Assistant serves from `brand/`: present, sized, transparent corners.

They are generated by `scripts/make_branding.py` and committed; this checks the committed
files against the brand-image rules (docs/BRANDING.md), not the script.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from PIL import Image

BRAND = Path(__file__).parents[1] / "custom_components" / "ksef_notification" / "brand"

ICONS = {"icon.png": 256, "icon@2x.png": 512}
LOGOS = {"logo.png": 256, "dark_logo.png": 256, "logo@2x.png": 512, "dark_logo@2x.png": 512}


def test_exactly_the_documented_images_ship() -> None:
    assert {path.name for path in BRAND.iterdir()} == set(ICONS) | set(LOGOS)


@pytest.mark.parametrize(("name", "side"), ICONS.items())
def test_an_icon_is_square_with_transparent_corners(name: str, side: int) -> None:
    with Image.open(BRAND / name) as image:
        assert image.format == "PNG"
        assert image.size == (side, side)
        rgba = image.convert("RGBA")
        corners = [(0, 0), (side - 1, 0), (0, side - 1), (side - 1, side - 1)]
        assert [rgba.getpixel(corner)[3] for corner in corners] == [0, 0, 0, 0]


@pytest.mark.parametrize(("name", "height"), LOGOS.items())
def test_a_logo_is_landscape_and_trimmed(name: str, height: int) -> None:
    """The shortest side of a logo is its height: 128 to 256, or 256 to 512 for @2x."""
    with Image.open(BRAND / name) as image:
        assert image.format == "PNG"
        assert image.height == height
        assert image.width > image.height
        rgba = image.convert("RGBA")
        assert rgba.getbbox() == (0, 0, image.width, image.height), "no empty margin"
